### ISSUE TITLE
[suggestion] follow python's case conventions

### ISSUE THREAD

**Issue by SeansC12** [Tophat-Guy99/HolyKeywordRevision#1]
Honestly variables and methods naming convention is a personal preference, but as per [PEP 8: Function and Variable names](https://peps.python.org/pep-0008/#function-and-variable-names),
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
> Variable names follow the same convention as function names. mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.

It's really up to you but by convention it may be better to put everything in snake_case.

**Comment by Tophat-Guy99** [comment]
Noted, ~~I shall continue to ignore PEP 8 because I will NEVER use snake_case until my life career is at stake~~ the reason the naming convention has been mangled beyond belief is because wrote the majority of this on a train and rushed it so I could revise other stuff.
